{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.frish2021",
    "module": "MineOldLoader",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MineOldLoader-1.3.1.jar",
          "url": "MineOldLoader-1.3.1.jar",
          "size": 22958,
          "sha512": "94716c7ba14690925f50fd8ffab9136ac9a9bc1902dd8d6585eec36945c611b372c0235f98ef73483ed2af28533fa6582e6f5b2b630f1a8da9a5040ebe9d9dee",
          "sha256": "abf864dd274a143928677e072989c4ddd4b1ef1398648c48b10112a0ae4238e4",
          "sha1": "e71ed7ff09738ac2cbb9c1579322ade9a776bdc0",
          "md5": "92b2f6cbeec5d54ff36a08a725081b23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "cn.frish2021",
          "module": "LaunchWrapper",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.5"
          }
        },
        {
          "group": "net.java.jinput",
          "module": "jinput",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "net.java.jutils",
          "module": "jutils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.lwjgl.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.lwjgl.lwjgl",
          "module": "lwjgl_util",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.0-beta9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.0-beta9"
          }
        }
      ],
      "files": [
        {
          "name": "MineOldLoader-1.3.1.jar",
          "url": "MineOldLoader-1.3.1.jar",
          "size": 22958,
          "sha512": "94716c7ba14690925f50fd8ffab9136ac9a9bc1902dd8d6585eec36945c611b372c0235f98ef73483ed2af28533fa6582e6f5b2b630f1a8da9a5040ebe9d9dee",
          "sha256": "abf864dd274a143928677e072989c4ddd4b1ef1398648c48b10112a0ae4238e4",
          "sha1": "e71ed7ff09738ac2cbb9c1579322ade9a776bdc0",
          "md5": "92b2f6cbeec5d54ff36a08a725081b23"
        }
      ]
    }
  ]
}
